sudo: false
jobs:
  fast_finish: true
  include:
    # build frontend
    - stage: build-frontend
      language: node_js
      node_js:
        - 14
      before_script:
        - cd frontend
      script:
        - yarn install
        - yarn build
      cache:
        yarn: true
        directories:
          - node_modules
    # TEST FRONTEND
    - stage: test-frontend
      language: node_js
      node_js:
        - 14
      before_script:
        - cd frontend
      script:
        - yarn global add codecov
        - yarn install
        - yarn serve &              # run app at bg
        - yarn test:e2e:ci          # test e2e
        - yarn test:unit:ci         # test unit
        - kill $(jobs -p) || true   # Kill all bg process
      cache:
        yarn: true
        directories:
          - node_modules

    - stage: push-frontend-docker-image
      language: ruby
      services:
        - docker
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      before_script:
        - cd api
      script:
        - docker build -t celebikutay/gotodo-frontend:latest .
        - docker push celebikutay/gotodo-frontend:latest

    # TEST API
    - stage: test-api
      language: go
      go:
        - 1.16.6
      before_script:
        - cd api
      script:
        - go mod download
        - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: push-api-docker-image
      language: ruby
      services:
        - docker
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      before_script:
        - cd api
      script:
        - docker build -t celebikutay/gotodo-api:latest .
        - docker push celebikutay/gotodo-frontend:latest
