version: "3"
services:
  db:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=tododb
  frontend:
    image: "celebikutay/gotodo-frontend:latest"
    restart: always
    ports:
    - 3000:3000
  api:
    image: "celebikutay/gotodo-api:latest"
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_USER=todo
      - DB_PASS=todo
      - GIN_MODE=test # set gin mode
