version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgresql-dev"
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}:todo
      - POSTGRES_PASSWORD=${DB_PASS}:todo
